### ISSUE TITLE
smart quotes: regexp like with smart_matchpairs? / no closing quote before `"`

### ISSUE THREAD

**Issue by blueyed** [Raimondi/delimitMate#164]
Currently delimitMate#IsSmartQuote uses a fixed pattern for the word_before / word_at check: `'\w\|[^[:punct:][:space:]]'`.

I suggest making this configurable like with `smart_matchpairs` and have a similar default: I was looking into it, because I would like to have no second quote before `$`.

**Comment by bdrewery** [comment]
I can't get this to work. I want to disable having `"` become `""` before `$something` in shell scripts.

**Comment by blueyed** [comment]
@bdrewery 
How are you trying to achieve it?
What are you using for `g:delimitMate_smart_quotes`?

**Comment by bdrewery** [comment]
I directly modified the default and added `$` (and `\$`) into the 2 `[]` lists and could not get it to do what I wanted.

For example:

<pre>
let default_smart_quotes = '\%(\w\|[^$[:punct:][:space:]' . quotes . ']\|\%(\\\\\)*\\\)\%#\|\%#\%(\w\|[^$[:space:][:punct:]' . quotes . ']\)'
</pre>

I'm sure I'm doing it wrong. It's confusing :)

Also, the directions for modifying the default `delimitMate_smart_quotes` seem stale since there is now a non-user-modifiable `quotes_list` list thrown in.

It would be simpler if there was just a list the user could modify of characters that will never have a quote started in front of it. I don't want to define the long default with my 1 `$` change for shell scripts with `b:` and risk losing good updates to the default in the future.

**Comment by blueyed** [comment]
@Raimondi ping
Can you shed some light into this, please?
What do you think about the above idea to simplify it?
